batch_size: 32
cuda_id: 0
dropout: 0.0251515151515151
features:
- chasmplus.csv
- vest.csv
- cadd.csv
- not_scored.csv
keep_training_n: 5 
lr: 0.0144776120660002
results_dir: 'models/train_dabrafenib_1_1'
save_grads: false
save_hiddens: false
save_model: true
test_file: ''
train_file: train_dabrafenib_nested_1_1.tsv
val_file: val_dabrafenib_nested_1_1.tsv
weight_decay: 0.001321941148466
